### ISSUE TITLE
Skipping IndelRealignment

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/Sarek#61]
According to multiple blogposts, indel realignment is not necessary for many variant callers by now. We should investigate once there are a couple of VCs integrated.

**Comment by szilvajuhos** [comment]
For HaplotypeCaller and MuTect1 it is still needed.

**Comment by marcelm** [comment]
According to Heng Li’s post at <https://www.biostars.org/p/135031/>, it’s not needed for HaplotypeCaller (he calls it gatk-hc in the post).

**Comment by MaxUlysse** [comment]
Could be interesting to have that for HC, more difficult for others callers

**Comment by szilvajuhos** [comment]
You are right, it is only MuTect1 than.

**Comment by MaxUlysse** [comment]
OK, good to know, as we will probably stop supporting MuTect1

**Comment by marcelm** [comment]
Perhaps this was implied by @szilvajuhos’s reply above, but to be explicit: [FreeBayes also does not need it](https://github.com/ekg/freebayes#best-practices-and-design-philosophy)

**Comment by marcelm** [comment]
I found a more or less official statement on indel realignment as part of the [GATK 3.6 release notes](https://software.broadinstitute.org/gatk/blog?id=7712):

> In the next few days we'll be making some updates to our Best Practices documentation to reflect updates to our production pipelines, and one thing you'll notice is that local realignment around indels is no longer included in the pre-processing part of the pipelines. More on that in a follow-up post; in a nutshell, indel realignment is just not useful enough anymore when you're calling variants with haplotype-based tools like HaplotypeCaller and MuTect2. This does mean we will no longer support the indel realignment tools as actively; but since others may care more about preserving and possibly even expanding this functionality, we've decided to move the relevant tools, IndelRealigner and RealignerTargetCreator, and related classes to the part of the GATK that is open-sourced under the MIT license.

**Comment by bjornnystedt** [comment]
Hi, 
for the record: it is clear that indel realignment is not needed for variant calling when running HaplotypeCaller or Mutect2 and we have known this since the beginning. For CAW, the decision was to use Strelka and Mutect1 as default (both needs indel realignment), based on the experience from the Oslo group and other benchmarks.  

One re-occuring key question is how good Mutect2 is; there have been previous posts indicating that Mutect2 was not yet mature and not very good for SNP-calling, and that Broad did not run it in production and actually did not recommend others to use it (although they were a bit ashamed to be very clear on this, but you could read inbetween the lines), and this is why have have not opted for that as default yet. We have all assumed that Mutect2 will mature at some point: Do we have solid “evidence” now that Mutect2 is mature enough to use in production, and replace Strelka/Mutect1? The blog post below does not quite convince me on that yet. We do not have the muscles to benchmark this ourselves in a convincing way, so we need to rely on others here. 

Best
Björn 


PS: As a side note; indel realignment takes a long time, but Mutect2 also takes a long time, so it seems the computational cost is not avoided, just moved to another step. But running first indel realignmen and then Mutect2 will of course add that computational cost twice.

Another side note; I have limited experience of looking at this, but I guess one drawback with the haplotype calling is that it might be harder to go back to the alignment to visually validate an individual call, since the alignment is post-procesed before the call is done, right? The actual calls should in principle be more accurate using haplotype calling, so the benefits should outweight the drawback, but still worth to keep in mind perhaps.



On 30 Mar 2017, at 18:45, Marcel Martin <notifications@github.com> wrote:

> I found a more or less official statement on indel realignment as part of the GATK 3.6 release notes:
> 
> In the next few days we'll be making some updates to our Best Practices documentation to reflect updates to our production pipelines, and one thing you'll notice is that local realignment around indels is no longer included in the pre-processing part of the pipelines. More on that in a follow-up post; in a nutshell, indel realignment is just not useful enough anymore when you're calling variants with haplotype-based tools like HaplotypeCaller and MuTect2. This does mean we will no longer support the indel realignment tools as actively; but since others may care more about preserving and possibly even expanding this functionality, we've decided to move the relevant tools, IndelRealigner and RealignerTargetCreator, and related classes to the part of the GATK that is open-sourced under the MIT license.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------------------------------------------------
Bjorn Nystedt, PhD
Manager, SciLifeLab Bioinformatics Long-term  Support (WABI)
www.scilifelab.se/facilities/wabi/

BMC E10:3206, entrance C11
Husargatan 3, SE-752 37 Uppsala

Phone: 018 - 471 4413
E-mail: bjorn.nystedt@scilifelab.se
------------------------------------------------

**Comment by szilvajuhos** [comment]
My experience so far with MuTect2 is: yeah, it is sub-optimal, but still better than most of other tools. Frankly, there are only few somatic callers out there that are giving decent calls _and_ are not a nightmare to install/run. 
Broads exome best practices somatic workflow uses MuTect2: https://software.broadinstitute.org/gatk/best-practices/mutect2.php It is a weak argument, but simply there is no well documented, and heavily validated WGS workflow out there as far as I see.

**Comment by bjornnystedt** [comment]
Ok, I guess we will discuss this again then on Wednesday :) 
(I will have to join remotely this time, sorry)

Best
Björn 

On 31 Mar 2017, at 09:33, Szilveszter Juhos <notifications@github.com> wrote:

> My experience so far with MuTect2 is: yeah, it is sub-optimal, but still better than most of other tools. Frankly, there are only few somatic callers out there that are giving decent calls and are not a nightmare to install/run.
> Broads exome best practices somatic workflow uses MuTect2: https://software.broadinstitute.org/gatk/best-practices/mutect2.php It is a weak argument, but simply there is no well documented, and heavily validated WGS workflow out there as far as I see.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------------------------------------------------
Bjorn Nystedt, PhD
Manager, SciLifeLab Bioinformatics Long-term  Support (WABI)
www.scilifelab.se/facilities/wabi/

BMC E10:3206, entrance C11
Husargatan 3, SE-752 37 Uppsala

Phone: 018 - 471 4413
E-mail: bjorn.nystedt@scilifelab.se
------------------------------------------------

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Think about skipping IndelRealignment](https://trello.com/c/NanSMmDG/35-think-about-skipping-indelrealignment)

**Comment by apeltzer** [comment]
#503  should make this anyways obsolete.

**Comment by MaxUlysse** [comment]
We will finally get rid of MuTecT1 #565
Since all other Variant Callers do not need this step, it will be definitively obsolete.

Please @malinlarsson can you confirm that AlleleCount and ASCAT does not need that.
