### ISSUE TITLE
Speed up FastQC

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/Sarek#631]
**FastQC can do multiple files at once, in multithreaded mode**
Now we are using the single-threaded mode for single files using a whole node (having 16 cpus)

Either use the -t option (see fastqc --help) or add a single CPU for each file, so they can be launched parallel

We can either feed all (or some number) of the fastq files and use the -t parameter, or assign a single CPU and run each file in parallel.

**Comment by MaxUlysse** [comment]
I think we talked about that with @alneberg yesterday
But yeah, we could completely improve that.
Do you want to take care of it yourself, or do you want to assign someone else to it?

**Comment by szilvajuhos** [comment]
As far as I understand, -t works on file basis: if there are 5 files, and we are assigning -t 16, it will use only 5 threads still (and extra GC threads, whatever). So, my suggestion would be first simply change the CPU requirement to 1, and have a look, how many processes are launched. Can I assign it to you @alneberg ?

**Comment by alneberg** [comment]
Yes go ahead assigning me to it. I will have a look at this for the sake of
ngi anyway. Happy to share any progress.

I think you are right in how the -t works though.

Den fre 31 aug. 2018 18:38Szilveszter Juhos <notifications@github.com>
skrev:

**Comment by alneberg** [comment]
I looked into a test run I did last week and it seems to use two threads when just adding '-t 16' to the current version. I believe that's because it has two fastq files: R1 and R2. The cleanest solution would be to add `-t 2` to the command and change to `cpus: 2` in the configs.

The alternative would be to launch one overarching fastqc process with files from different samples, but I don't see the reason to make it that complicated?

Any comments?

**Comment by szilvajuhos** [comment]
Looks reasonable, go ahead.

**Comment by MaxUlysse** [comment]
Sounds like a good idea.

**Comment by MaxUlysse** [comment]
closed by #632
