### ISSUE TITLE
ASCAT with WES

### ISSUE THREAD

**Issue by Anuragksingh** [SciLifeLab/Sarek#763]
Hello, 
I had some doubts over [...] ascat. It would be really helpful if you can provide some insights about that.
[...]
Can we use the available ascat directly on WES data. I guess the creation of  BAF and LogR  files from bam  would be same for WES data also. Or do we need to apply additional filters to use ascat on WES data?
For reference kindly see this link:
https://github.com/Crick-CancerGenomics/ascat/issues/19

Any suggestions on above aspects would be really helpful.

Thanks

From another issue
> Also does we need to add --exome flag when running ascat on WES data?

EDIT by @MaxUlysse: I moved the first part of this question into #764

**Comment by MaxUlysse** [comment]
Hi @Anuragksingh 
Running ASCAT for WES is definitively something that we're thinking about.
I remember reading about this link before, I'll definitively look more into it.
Thanks again for all your interest in this project

**Comment by MaxUlysse** [comment]
From @szilvajuhos :
> to run ASCAT on exome you will need a separate file of SNPs that is covering the targeted exons only

**Comment by dingxm** [comment]
Hi,
We are tyring to analyze exome data for copy number.  The exome data has extended probes covering regions outside of the exomes. It seems that last year ASCAT could not use exome data without pre-processing, is this still true or is there a version that deals with Exome data now?

Also, can pooled normals be used in place of matched normal?  If so, how could this be done.

Thank You,

**Comment by szilvajuhos** [comment]
Hej, 
If you have a BED file that is covering your WES target, I would recommend to make a .loci file i.e. by filtering the latest dbSNP for common biallelic SNPs that are overlapping your target. You have to have quite a few loci positions (since the target is smaller and the genome is not covered evenly) to make sure you will still have enough SNPs. @malinlarsson is better in playing with it, the .loci file I have created contains ~16M lines:

```
$ wc -l dbSNP_151_S04380110_AllExonV5_hg38.loci
16200625
$ head -3 dbSNP_151_S04380110_AllExonV5_hg38.loci
chr1    65529
chr1    65552
chr1    65591
```
We have managed to make meaningful charts with this loci file (I can share it if you want to give a try), but certainly it is only the beginning of finding the right settings.

As for pooled normals: I have no idea, we are using only tumour/normal pairs.

**Comment by MaxUlysse** [comment]
Transferred to the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
