### ISSUE TITLE
Max CPUs Workstation Utilization

### ISSUE THREAD

**Issue by kokyriakidis** [SciLifeLab/Sarek#767]
Hello,
When I run the pipeline with singularity profile on my local workstation with 10 cores and 20 threads I see that fastqc and bwa run on 2 cores each only and not use the max cpus stated at base.config file. Why is that? Can I change it in order to take full advantage of my resources?

**Comment by KochTobi** [comment]
The problem is that, depending on your profile, there is no process specific resource definition in the standard profiles (see #760 ). `max_cpus` only provide an upper limit. You can change your profile or provide a local profile file with settings comparable to https://github.com/SciLifeLab/Sarek/blob/master/conf/uppmax-localhost.config. Alternatively you could include the https://github.com/SciLifeLab/Sarek/blob/master/conf/resources.config file into your profile or add the following lines:
```
process {
  cpus = { check_max( 10, 'cpus' ) }
  memory = { check_max( 16.GB * task.attempt, 'memory' ) }
  time = { check_max( 8.h * task.attempt, 'time' ) }
  
  // or per process
  withName:RunFastQC {
    cpus = { check_max(10,'cpus') }
  }
  withName:MapReads {
    cpus = { check_max(10,'cpus') }
  }
}
```

**Comment by kokyriakidis** [comment]
So, since I have not downloaded anything, should I just clone this resource.config in my workspace and define it in the nextflow command using -c?

**Comment by KochTobi** [comment]
Yes that would be one solution. I guess we should move the content of this file or a refined version into the base.config. But for now I think it is the easiest option.

**Comment by KochTobi** [comment]
You could also create a file and put
```
process {
  cpus = params.max_cpus
  memory = params.max_memory
}
```
into it. And load that one with `-c`

**Comment by kokyriakidis** [comment]
Thank you very much! It would be very helpful for the user to set the parameter --max_cpus in the nextflow command. Thanks for the help!

**Comment by kokyriakidis** [comment]
> You could also create a file and put
> 
> ```
> process {
>   cpus = params.max_cpus
>   memory = params.max_memory
> }
> ```
> into it. And load that one with `-c`

If I create a file like that, can I set the parameter --max_cpus in nextflow command in order to change the base.config default? (16 cores)
